all:
	g++ -ggdb3 -o  shm shm.cpp -lrt
	g++ -ggdb3 -o  shm_svr shm_svr.cpp -lrt
	g++ -ggdb3 -o  shm_cli shm_cli.cpp -lrt
	g++ -ggdb3 -o  stat_svr stat_svr.cpp -lrt
	g++ -ggdb3 -o  stat_cli stat_cli.cpp -lrt
	g++ -ggdb3 -o  stat_view stat_view.cpp -lrt
